name: branch

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install node
        uses: actions/setup-node@v6
      - name: install pug & build
        run: |
          npm install pug-cli -g
          pug --pretty -o site/flicksy3 --basedir src -- src/index.pug
      - name: upload page
        uses: actions/upload-artifact@v6
        with:
          name: flicksy3.html
          path: ./site/flicksy3/index.html
